name: mstech_test
description: "Flutter app — Feature-First + Clean Architecture + Riverpod"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.13.0-104.0.dev

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  lottie: ^3.3.1

  # State management
  flutter_riverpod: ^3.3.1
  riverpod_annotation: ^4.0.2

  # Navigation
  go_router: ^14.8.1

  # Data classes
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

  # Persistence
  shared_preferences: ^2.5.3

  # Links
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.15
  freezed: ^3.2.5
  json_serializable: ^6.9.5
  riverpod_generator: ^4.0.3


flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
